name: Atualizar Dados do TomTicket

on:
  schedule:
    # Agenda para rodar de 20 em 20 minutos automaticamente
    - cron: "*/20 * * * *"
  workflow_dispatch: # Permite que você force a atualização clicando em um botão no GitHub se quiser

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Consultar API do TomTicket e gerar JSON
        run: |
          # Faz a chamada oficial com o Token primeiro, seguido pela página 1
          curl -X GET "https://api.tomticket.com/v1/chamados/${{ secrets.TOMTICKET_TOKEN }}/1" \
          -H "accept: application/json" \
          -o dados.json

      - name: Salvar e publicar os dados atualizados
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dados.json
          # Só faz o commit se houver alguma diferença nos dados para evitar commits vazios
          git diff-index --quiet HEAD || git commit -m "data: Atualização automatizada dos chamados"
          git push
